 name: Latest Hashnode Activity
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest activity from hashnode
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in hashnode posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "HASHNODE"
          commit_message: "Updated readme with the latest hashnode data"
          feed_list: "https://mayourwa.hashnode.dev/rss.xml"